using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._NC.DiscordAuth.DiscordGui;

[GenerateTypedNameReferences]
public sealed partial class DiscordAuthGui : Control
{
    [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
    [Dependency] private readonly DiscordAuthManager _discordAuthManager = default!;
    [Dependency] private readonly IUriOpener _uriOpener = default!;

    public DiscordAuthGui()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);

        QuitButton.OnPressed += _ =>
        {
            _consoleHost.ExecuteCommand("quit");
        };

        AuthorizeButton.OnPressed += _ =>
        {
            // Открываем ссылку в браузере через IUriOpener
            if (!string.IsNullOrEmpty(_discordAuthManager.AuthLink))
            {
                _uriOpener.OpenUri(_discordAuthManager.AuthLink);
            }
            else
            {
                // Fallback ссылка
                _uriOpener.OpenUri("https://discord.gg/cncwdkTWRK");
            }
        };
    }
}
